### ISSUE TITLE
Require old versions of dependencies to work

### ISSUE THREAD

**Issue by IzK666** [scaidermern/piCamBot#9]
I have followed your instructions in a new raspbian installation because my old SD card went wrong.
To make it work, I needed old versions of two dependencies.
`pip3 install python-telegram-bot==10.1.0`
`pip3 install inotify==0.2.8`

Maybe you want to note it on README.md

**Comment by scaidermern** [comment]
Thanks for the information!

Unfortunately I didn't spend much time on piCamBot lately. I hope to update the code soon in order to fix this.

**Comment by scaidermern** [comment]
I've updated the code to support the newest version of python-telegram-bot and inotify.

piCamBot now requires python3 (python-telegram-bot has dropped support for python2 and python2 has reached end of life).

In case you are using GPIO (for PIR or a buzzer) please note that you have to update the GPIO numbers in your config.json. Previously piCamBot used the board numbering scheme for GPIOs but now it uses the BCM numbering scheme, which seems to be more common.
